variable "region" {}
variable "cidr" {}
variable "project_name" {}
variable "team" {}
variable "routetable_cidr" {}
variable "sg_ports_alb_ingress" {}
variable "sg_ports_alb_egress" {}
variable "sg_ports_ecs_ingress" {}
variable "sg_ports_ecs_egress" {}